/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author GOWTHAM V BHAT
 */
public class Frame_ProductDetails extends javax.swing.JFrame {

    /**
     * Creates new form Frame_ProductDetails
     */
    public Frame_ProductDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //This method disposes the current JFrame when Close(X) button is clicked instead of Exiting the program.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_PBPID = new javax.swing.JLabel();
        jTextField_PBPID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_PBCN = new javax.swing.JTextField();
        jTextField_PBMtr = new javax.swing.JTextField();
        jTextField_PBName = new javax.swing.JTextField();
        jTextField_PBClr = new javax.swing.JTextField();
        jTextField_PBCpt = new javax.swing.JTextField();
        jTextField_PBDNO = new javax.swing.JTextField();
        jTextField_PBStk = new javax.swing.JTextField();
        jTextField_PBPRC = new javax.swing.JTextField();
        jTextField_PBGST = new javax.swing.JTextField();
        jLabel_PBSearch = new javax.swing.JLabel();
        jTextField_PBSearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton_Pidd = new javax.swing.JButton();
        jTextField_PIDD = new javax.swing.JTextField();
        jButton_DB = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel_PBSearch1 = new javax.swing.JLabel();
        jTextField_PUS = new javax.swing.JTextField();
        jButton_PUS = new javax.swing.JButton();
        jLabel_PBPID1 = new javax.swing.JLabel();
        jTextField_PUPID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_PUName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField_PUCN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField_PUMtr = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_PUClr = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_PUCpt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_PUDNO = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_PUStk = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_PUPRC = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField_PUGST = new javax.swing.JTextField();
        jButton_PUCNL = new javax.swing.JButton();
        jButton_PUDT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_PID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_CName = new javax.swing.JTextField();
        jTextField_MT = new javax.swing.JTextField();
        jTextField_PName = new javax.swing.JTextField();
        jTextField_CL = new javax.swing.JTextField();
        jTextField_CP = new javax.swing.JTextField();
        jTextField_DNo = new javax.swing.JTextField();
        jTextField_STK = new javax.swing.JTextField();
        jTextField_PRC = new javax.swing.JTextField();
        jTextField_GST = new javax.swing.JTextField();
        jButton_PCL = new javax.swing.JButton();
        jButton_PAD = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Back Icon.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Details");

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/List Icon.png"))); // NOI18N
        jButton3.setText(" List");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.setForeground(new java.awt.Color(101, 101, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_PBPID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_PBPID.setForeground(new java.awt.Color(101, 101, 0));
        jLabel_PBPID.setText("Product ID:");

        jTextField_PBPID.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBPID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBPID.setForeground(new java.awt.Color(101, 101, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 101, 0));
        jLabel13.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(101, 101, 0));
        jLabel14.setText("Material:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(101, 101, 0));
        jLabel15.setText("Company Name:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(101, 101, 0));
        jLabel16.setText("Color:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(101, 101, 0));
        jLabel17.setText("Capacity:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(101, 101, 0));
        jLabel18.setText("Department No:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(101, 101, 0));
        jLabel19.setText("Stock:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(101, 101, 0));
        jLabel20.setText("Price:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(101, 101, 0));
        jLabel21.setText("GST:");

        jTextField_PBCN.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBCN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBCN.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBMtr.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBMtr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBMtr.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBName.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBName.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBClr.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBClr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBClr.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBCpt.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBCpt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBCpt.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBDNO.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBDNO.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBDNO.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBStk.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBStk.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBStk.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBPRC.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBPRC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBPRC.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PBGST.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBGST.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBGST.setForeground(new java.awt.Color(101, 101, 0));

        jLabel_PBSearch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_PBSearch.setForeground(new java.awt.Color(101, 101, 0));
        jLabel_PBSearch.setText("Product ID :");

        jTextField_PBSearch.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PBSearch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PBSearch.setForeground(new java.awt.Color(101, 101, 0));

        jButton4.setBackground(new java.awt.Color(0, 153, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Search table icon.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel_PBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField_PBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_PBPID, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_PBName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_PBPID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_PBMtr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBClr, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBCN, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel18))
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_PBDNO, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBCpt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBGST, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBPRC, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBStk, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_PBCpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_PBDNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_PBStk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField_PBPRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_PBGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField_PBClr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PBPID)
                            .addComponent(jTextField_PBPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_PBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_PBCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_PBMtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Browse", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton_Pidd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_Pidd.setForeground(new java.awt.Color(101, 101, 0));
        jButton_Pidd.setText("Product ID :");
        jButton_Pidd.setContentAreaFilled(false);
        jButton_Pidd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Pidd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PiddActionPerformed(evt);
            }
        });

        jTextField_PIDD.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PIDD.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PIDD.setForeground(new java.awt.Color(101, 101, 0));
        jTextField_PIDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PIDDActionPerformed(evt);
            }
        });

        jButton_DB.setBackground(new java.awt.Color(0, 153, 204));
        jButton_DB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_DB.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Delete from table icon.png"))); // NOI18N
        jButton_DB.setText("Delete");
        jButton_DB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(jButton_Pidd)
                .addGap(18, 18, 18)
                .addComponent(jTextField_PIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jButton_DB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Pidd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_DB, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(593, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_PBSearch1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_PBSearch1.setForeground(new java.awt.Color(101, 101, 0));
        jLabel_PBSearch1.setText("Product ID :");

        jTextField_PUS.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUS.setForeground(new java.awt.Color(101, 101, 0));

        jButton_PUS.setBackground(new java.awt.Color(0, 153, 204));
        jButton_PUS.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_PUS.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Search table icon.png"))); // NOI18N
        jButton_PUS.setText("Search");
        jButton_PUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PUSMouseClicked(evt);
            }
        });

        jLabel_PBPID1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_PBPID1.setForeground(new java.awt.Color(101, 101, 0));
        jLabel_PBPID1.setText("Product ID:");

        jTextField_PUPID.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUPID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUPID.setForeground(new java.awt.Color(101, 101, 0));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(101, 101, 0));
        jLabel22.setText("Name:");

        jTextField_PUName.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUName.setForeground(new java.awt.Color(101, 101, 0));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(101, 101, 0));
        jLabel23.setText("Company Name:");

        jTextField_PUCN.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUCN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUCN.setForeground(new java.awt.Color(101, 101, 0));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(101, 101, 0));
        jLabel24.setText("Material:");

        jTextField_PUMtr.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUMtr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUMtr.setForeground(new java.awt.Color(101, 101, 0));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(101, 101, 0));
        jLabel25.setText("Color:");

        jTextField_PUClr.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUClr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUClr.setForeground(new java.awt.Color(101, 101, 0));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(101, 101, 0));
        jLabel26.setText("Capacity:");

        jTextField_PUCpt.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUCpt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUCpt.setForeground(new java.awt.Color(101, 101, 0));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(101, 101, 0));
        jLabel27.setText("Department No:");

        jTextField_PUDNO.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUDNO.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUDNO.setForeground(new java.awt.Color(101, 101, 0));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(101, 101, 0));
        jLabel28.setText("Stock:");

        jTextField_PUStk.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUStk.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUStk.setForeground(new java.awt.Color(101, 101, 0));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(101, 101, 0));
        jLabel29.setText("Price:");

        jTextField_PUPRC.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUPRC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUPRC.setForeground(new java.awt.Color(101, 101, 0));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(101, 101, 0));
        jLabel30.setText("GST:");

        jTextField_PUGST.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PUGST.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PUGST.setForeground(new java.awt.Color(101, 101, 0));

        jButton_PUCNL.setBackground(new java.awt.Color(255, 51, 51));
        jButton_PUCNL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_PUCNL.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PUCNL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Cancel product icon.png"))); // NOI18N
        jButton_PUCNL.setText("Cancel");
        jButton_PUCNL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_PUDT.setBackground(new java.awt.Color(0, 153, 204));
        jButton_PUDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_PUDT.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PUDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Update table icon.png"))); // NOI18N
        jButton_PUDT.setText("Update");
        jButton_PUDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_PUDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PUDTMouseClicked(evt);
            }
        });
        jButton_PUDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PUDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PBSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField_PUS, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton_PUS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel_PBPID1))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_PUName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PUPID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_PUClr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PUMtr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PUCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_PUDT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_PUGST, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PUPRC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton_PUCNL, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(278, 278, 278)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jTextField_PUCpt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_PUDNO, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField_PUStk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PBSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_PUS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextField_PUCpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_PUDNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_PUStk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextField_PUPRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextField_PUGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_PUCNL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_PUDT, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel24)
                                .addGap(72, 72, 72))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jTextField_PUCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jTextField_PUMtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_PBPID1)
                                    .addComponent(jTextField_PUPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_PUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextField_PUClr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))))
        );

        jTabbedPane1.addTab("Update", jPanel6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 101, 0));
        jLabel2.setText("Product ID:");

        jTextField_PID.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PID.setForeground(new java.awt.Color(101, 101, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 101, 0));
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 101, 0));
        jLabel4.setText("Material:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 101, 0));
        jLabel5.setText("Company Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 101, 0));
        jLabel6.setText("Color:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(101, 101, 0));
        jLabel7.setText("Capacity:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(101, 101, 0));
        jLabel8.setText("Department No:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(101, 101, 0));
        jLabel9.setText("Stock:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(101, 101, 0));
        jLabel10.setText("Price:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(101, 101, 0));
        jLabel11.setText("GST:");

        jTextField_CName.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_CName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_CName.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_MT.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_MT.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_MT.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PName.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PName.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_CL.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_CL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_CL.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_CP.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_CP.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_CP.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_DNo.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_DNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_DNo.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_STK.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_STK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_STK.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_PRC.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_PRC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_PRC.setForeground(new java.awt.Color(101, 101, 0));

        jTextField_GST.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_GST.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_GST.setForeground(new java.awt.Color(101, 101, 0));

        jButton_PCL.setBackground(new java.awt.Color(255, 51, 51));
        jButton_PCL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_PCL.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PCL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Cancel product icon.png"))); // NOI18N
        jButton_PCL.setText("Cancel");
        jButton_PCL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton_PAD.setBackground(new java.awt.Color(0, 153, 204));
        jButton_PAD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_PAD.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Add to table icon.png"))); // NOI18N
        jButton_PAD.setText("Add");
        jButton_PAD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_PAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PADMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Add to table icon.png"))); // NOI18N
        jButton1.setText("Add Another Product");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(992, 992, 992))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(248, 248, 248)
                                .addComponent(jButton_PAD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton_PCL, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_GST, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PRC, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_STK, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_DNo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(85, 85, 85))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_CName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_PName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField_MT, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_PID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_STK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_MT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_PRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_CL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_GST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_DNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_PAD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_PCL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );

        jTabbedPane1.addTab("Add", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       new Frame_HomePage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton_PiddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PiddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PiddActionPerformed

    private void jTextField_PIDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PIDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PIDDActionPerformed

    private void jButton_PADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PADMouseClicked
            String pid = jTextField_PID.getText();
            String name = jTextField_PName.getText();
            String com_name = jTextField_CName.getText();
            String material = jTextField_MT.getText();
            String color = jTextField_CL.getText();
            String capacity = jTextField_CP.getText();
            String dep_no = jTextField_DNo.getText();   
            String stock = jTextField_STK.getText();    
            String price = jTextField_PRC.getText();   
            String gst = jTextField_GST.getText();          
                        
            
            
            try {
            Connection cn = MyConnection.getConnection();
            Statement psa =  cn.createStatement();
            double i = psa.executeUpdate("INSERT INTO `product`(`product_id`, `name`, `company_name`, `material`, `color`, `capacity`, `dno`, `stock`, `price`, `gst`) VALUES ('"+pid+"', '"+name+"', '"+com_name+"', '"+material+"', '"+color+"', '"+capacity+"', '"+dep_no+"', '"+stock+"', '"+price+"', '"+gst+"')");
            
            if ( i > 0)
            {   
               JOptionPane.showMessageDialog(null, "new product added");
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "No Input or Invalid Input");
            }
        }   
        catch (SQLException ex) {
            Logger.getLogger(Frame_ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_PADMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            new Frame_ProductDetails().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
            
            /* String pid = "pid";
            String name = "name";
            String com_name = "com_name";
            String material = "material";
            String color = "color";
            String capacity = "capacity";
            String dep_no = "dep_no";   
            String stock = "stock";    
            String price = "price";   
            String gst = "gst"; */
        
            ResultSet rspb = null;
            rspb = MyResultSet.find(jTextField_PBSearch.getText());
            
            try{
                if(rspb.next()) {
                    jTextField_PBPID.setText(rspb.getString("product_id"));                    //the word inside the quotes are attrubute names.
                    jTextField_PBName.setText(rspb.getString("name"));
                    jTextField_PBCN.setText(rspb.getString("company_name"));
                    jTextField_PBMtr.setText(rspb.getString("material"));
                    jTextField_PBClr.setText(rspb.getString("color"));
                    jTextField_PBCpt.setText(rspb.getString("capacity"));
                    jTextField_PBDNO.setText(rspb.getString("dno"));
                    jTextField_PBStk.setText(rspb.getString("stock"));
                    jTextField_PBPRC.setText(rspb.getString("price"));
                    jTextField_PBGST.setText(rspb.getString("gst"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
                }
            }
            
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton_DBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DBMouseClicked
            String pidd = jTextField_PIDD.getText();
            
            try{
                
                Statement csd = MyConnection.getConnection().createStatement();
                
                double j = csd.executeUpdate("DELETE FROM `product` WHERE product_id = '"+pidd+"'");
                
                if( j > 0 )
                {
                    JOptionPane.showMessageDialog(null, "Product Deleted Successfully");
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
                }
            }
            
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }    
    }//GEN-LAST:event_jButton_DBMouseClicked

    private void jButton_PUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PUSMouseClicked
            ResultSet rspb = null;
            rspb = MyResultSet.find(jTextField_PBSearch.getText());
            
            try{
                if(rspb.next()) {
                    jTextField_PUPID.setText(rspb.getString("product_id"));                    //the word inside the quotes are attrubute names.
                    jTextField_PUName.setText(rspb.getString("name"));
                    jTextField_PUCN.setText(rspb.getString("company_name"));
                    jTextField_PUMtr.setText(rspb.getString("material"));
                    jTextField_PUClr.setText(rspb.getString("color"));
                    jTextField_PUCpt.setText(rspb.getString("capacity"));
                    jTextField_PUDNO.setText(rspb.getString("dno"));
                    jTextField_PUStk.setText(rspb.getString("stock"));
                    jTextField_PUPRC.setText(rspb.getString("price"));
                    jTextField_PUGST.setText(rspb.getString("gst"));
                }
                else{
                    JOptionPane.showMessageDialog(null, "NO DATA FOR THIS ID");
                }
            }
            
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
    }//GEN-LAST:event_jButton_PUSMouseClicked

    private void jButton_PUDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PUDTMouseClicked
            String pid = jTextField_PUPID.getText();
            String name = jTextField_PUName.getText();
            String com_name = jTextField_PUCN.getText();
            String material = jTextField_PUMtr.getText();
            String color = jTextField_PUClr.getText();
            String capacity = jTextField_PUCpt.getText();
            String dep_no = jTextField_PUDNO.getText();   
            String stock = jTextField_PUStk.getText();    
            String price = jTextField_PUPRC.getText();   
            String gst = jTextField_PUGST.getText();          
                        
            
            
            try {
            Connection cn = MyConnection.getConnection();
            Statement psa =  cn.createStatement();
            double i = psa.executeUpdate("UPDATE `product` SET `name`='"+name+"', `company_name`='"+com_name+"', `material`='"+material+"', `color`='"+color+"', `capacity`='"+capacity+"', `dno`='"+dep_no+"', `stock`='"+stock+"', `price`='"+price+"', `gst`='"+gst+"' WHERE `product_id`='"+pid+"'");
            
            if ( i > 0)
            {   
               JOptionPane.showMessageDialog(null, "Data updated successfully");
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "No Input or Invalid Input");
            }
        }   
        catch (SQLException ex) {
            Logger.getLogger(Frame_ProductDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_PUDTMouseClicked

    private void jButton_PUDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PUDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PUDTActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
            JFrame current = new Frame_ListProduct();
            current.setVisible(true);
            
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_DB;
    private javax.swing.JButton jButton_PAD;
    private javax.swing.JButton jButton_PCL;
    private javax.swing.JButton jButton_PUCNL;
    private javax.swing.JButton jButton_PUDT;
    private javax.swing.JButton jButton_PUS;
    private javax.swing.JButton jButton_Pidd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_PBPID;
    private javax.swing.JLabel jLabel_PBPID1;
    private javax.swing.JLabel jLabel_PBSearch;
    private javax.swing.JLabel jLabel_PBSearch1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_CL;
    private javax.swing.JTextField jTextField_CName;
    private javax.swing.JTextField jTextField_CP;
    private javax.swing.JTextField jTextField_DNo;
    private javax.swing.JTextField jTextField_GST;
    private javax.swing.JTextField jTextField_MT;
    private javax.swing.JTextField jTextField_PBCN;
    private javax.swing.JTextField jTextField_PBClr;
    private javax.swing.JTextField jTextField_PBCpt;
    private javax.swing.JTextField jTextField_PBDNO;
    private javax.swing.JTextField jTextField_PBGST;
    private javax.swing.JTextField jTextField_PBMtr;
    private javax.swing.JTextField jTextField_PBName;
    private javax.swing.JTextField jTextField_PBPID;
    private javax.swing.JTextField jTextField_PBPRC;
    private javax.swing.JTextField jTextField_PBSearch;
    private javax.swing.JTextField jTextField_PBStk;
    private javax.swing.JTextField jTextField_PID;
    private javax.swing.JTextField jTextField_PIDD;
    private javax.swing.JTextField jTextField_PName;
    private javax.swing.JTextField jTextField_PRC;
    private javax.swing.JTextField jTextField_PUCN;
    private javax.swing.JTextField jTextField_PUClr;
    private javax.swing.JTextField jTextField_PUCpt;
    private javax.swing.JTextField jTextField_PUDNO;
    private javax.swing.JTextField jTextField_PUGST;
    private javax.swing.JTextField jTextField_PUMtr;
    private javax.swing.JTextField jTextField_PUName;
    private javax.swing.JTextField jTextField_PUPID;
    private javax.swing.JTextField jTextField_PUPRC;
    private javax.swing.JTextField jTextField_PUS;
    private javax.swing.JTextField jTextField_PUStk;
    private javax.swing.JTextField jTextField_STK;
    // End of variables declaration//GEN-END:variables
}
