/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Team137
 */
public class Frame_ListProduct extends javax.swing.JFrame {

    /**
     * Creates new form Frame_ListProduct
     */
    public Frame_ListProduct() {
        initComponents();
        jTable_ProductList.getTableHeader().setFont(new Font("Tahoma",0, 18));  //to set the font for TJTable Header
        
        this.setLocationRelativeTo(null);
        show_prod();
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //This method disposes the current JFrame when Close(X) button is clicked instead of Exiting the program.
    }
    
    public ArrayList<Product> productList() {
        ArrayList<Product> productsList = new ArrayList<>();
        
        String word = "01";
        try {    
            Statement list = MyConnection.getConnection().createStatement();
        
            ResultSet rs = list.executeQuery("SELECT * FROM `product` WHERE product_id LIKE '%"+word+"%'");
            
            Product prod;
            
            while(rs.next())
            {
                prod = new Product(rs.getString("product_id"), rs.getString("name"), rs.getString("company_name"), rs.getString("material"), rs.getString("color"), rs.getString("capacity"), rs.getString("dno"), rs.getString("stock"), rs.getString("price"), rs.getString("gst"));
                productsList.add(prod);
            }
                    
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        return productsList;
    }

    public void show_prod() {
        
        //COde to increase the JTable header Font

        
        ArrayList<Product> plist = productList();
        DefaultTableModel model = (DefaultTableModel)jTable_ProductList.getModel();  //typecasting
        Object[] row = new Object[10];
        for(int i=0; i<plist.size(); i++)
        {
            row[0] = plist.get(i).getpid();
            row[1] = plist.get(i).getname();
            row[2] = plist.get(i).getcom_name();
            row[3] = plist.get(i).getmaterial();
            row[4] = plist.get(i).getcolor();
            row[5] = plist.get(i).getcapacity();
            row[6] = plist.get(i).getdno();
            row[7] = plist.get(i).getstock();
            row[8] = plist.get(i).getprice();
            row[9] = plist.get(i).getgst();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ProductList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable_ProductList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_ProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_Id", "Name", "Company Name", "Material", "Color", "Capacity", "Department No", "Stock", "Price", "GST"
            }
        ));
        jTable_ProductList.setRowHeight(19);
        jScrollPane1.setViewportView(jTable_ProductList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ListProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ListProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ListProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ListProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ListProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ProductList;
    // End of variables declaration//GEN-END:variables
}
