/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.Date;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author GOWTHAM V BHAT
 */
public class Frame_Register extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Register
     */
    public Frame_Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_RUN = new javax.swing.JTextField();
        jTextField_RN = new javax.swing.JTextField();
        jButton_RC = new javax.swing.JButton();
        jButton_RReg = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser_Date = new com.toedter.calendar.JDateChooser();
        jPasswordField_RRP = new javax.swing.JPasswordField();
        jPasswordField_RP = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(501, 501, 501))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 101, 0));
        jLabel3.setText("Username : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(101, 101, 0));
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 101, 0));
        jLabel5.setText("Password : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 101, 0));
        jLabel6.setText("Retype Pass : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(101, 101, 0));
        jLabel7.setText("DOB : ");

        jTextField_RUN.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_RUN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_RUN.setForeground(new java.awt.Color(101, 101, 0));
        jTextField_RUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RUNActionPerformed(evt);
            }
        });

        jTextField_RN.setBackground(new java.awt.Color(255, 255, 102));
        jTextField_RN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_RN.setForeground(new java.awt.Color(101, 101, 0));
        jTextField_RN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RNActionPerformed(evt);
            }
        });

        jButton_RC.setBackground(new java.awt.Color(255, 51, 51));
        jButton_RC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_RC.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Cancel Register icon.png"))); // NOI18N
        jButton_RC.setText("Cancel");
        jButton_RC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_RC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RCMouseClicked(evt);
            }
        });

        jButton_RReg.setBackground(new java.awt.Color(0, 153, 204));
        jButton_RReg.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton_RReg.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Register Icon.png"))); // NOI18N
        jButton_RReg.setText("Register");
        jButton_RReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_RReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RRegMouseClicked(evt);
            }
        });
        jButton_RReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RRegActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(101, 101, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/Click here icon.png"))); // NOI18N
        jLabel8.setText("Click here to Login");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jDateChooser_Date.setBackground(new java.awt.Color(255, 255, 102));
        jDateChooser_Date.setDateFormatString("d-MMM-yyyy");

        jPasswordField_RRP.setBackground(new java.awt.Color(255, 255, 102));
        jPasswordField_RRP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_RRP.setForeground(new java.awt.Color(101, 101, 0));
        jPasswordField_RRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_RRPActionPerformed(evt);
            }
        });

        jPasswordField_RP.setBackground(new java.awt.Color(255, 255, 102));
        jPasswordField_RP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_RP.setForeground(new java.awt.Color(101, 101, 0));
        jPasswordField_RP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_RPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_RC, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton_RReg))
                    .addComponent(jTextField_RUN)
                    .addComponent(jTextField_RN)
                    .addComponent(jDateChooser_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField_RRP)
                    .addComponent(jPasswordField_RP))
                .addGap(399, 399, 399))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(427, 427, 427))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_RN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_RUN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_RP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_RRP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jDateChooser_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_RC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_RReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_RUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RUNActionPerformed

    private void jTextField_RNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RNActionPerformed

    private void jButton_RRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RRegMouseClicked
        
        String name = jTextField_RN.getText();
        String username = jTextField_RUN.getText();
        String pw = String.valueOf(jPasswordField_RP.getPassword());
        String rpw = String.valueOf(jPasswordField_RRP.getPassword());
        
        //SimpleDateFormat date = new SimpleDateFormat("dd-MMM-yyyy");
        java.sql.Date date = new java.sql.Date(jDateChooser_Date.getDate().getTime()); 
       
        if(username.equals("") || name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Username & Name fields cannot be empty");
            new Frame_Register().setVisible(true);
            this.dispose();
        }
        
        else {
            if(pw.equals(rpw)){
                try {
                    Connection cn = MyConnection.getConnection();
                    Statement psa =  cn.createStatement();
                    double i = psa.executeUpdate("INSERT INTO `user`(`name`, `username`, `password`, `dob`) VALUES ('"+name+"', '"+username+"', '"+pw+"', '"+date+"')");
            
                    if ( i > 0)
                    {   
                       JOptionPane.showMessageDialog(null, "Account created successfully");
                    }
            
                    else
                    {
                    JOptionPane.showMessageDialog(null, "Registration failed");
                    }
                }
        
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        
            else
            {
                JOptionPane.showMessageDialog(null, "Password Mismatch, pw: "+pw+" rpw: "+rpw);
                new Frame_Register().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton_RRegMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new Frame_Login().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton_RCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RCMouseClicked
        new Frame_Register().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_RCMouseClicked

    private void jPasswordField_RRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_RRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_RRPActionPerformed

    private void jPasswordField_RPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_RPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_RPActionPerformed

    private void jButton_RRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RC;
    private javax.swing.JButton jButton_RReg;
    private com.toedter.calendar.JDateChooser jDateChooser_Date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_RP;
    private javax.swing.JPasswordField jPasswordField_RRP;
    private javax.swing.JTextField jTextField_RN;
    private javax.swing.JTextField jTextField_RUN;
    // End of variables declaration//GEN-END:variables
}
